### PR TITLE
Build should fail when reutrn status is !0

### PR DESCRIPTION
**Pull request by tsheasha**

### CODE REVIEW

**Comment by tiras-j** [comment]
Do we want to exit as soon as we fail once or run all the tests and then exit with failure if something failed? Might give a bit more information on a failure, but I don't feel strongly one way or the other.

**Comment by tsheasha** [comment]
information on failure is already displayed check before my change ... https://travis-ci.org/Yelp/fullerite/builds/95366763 for example. However i think we don't need to do any more tests if we fail anyways, since the build will fail anyways.

**Comment by gnufied** [comment]
:shipit:

**Comment by tiras-j** [comment]
@tsheasha Yea that's what I meant. Currently it'll only display the failure message for the first failed test since it will exit immediately following that failure. I'm just thinking that if a subsequent test would also fail the current setup would require fixing a single failure and then pushing again before discovering the next. 

Then again, since the tests are at package level fidelity... if you have that many failures and you're trying to push you're doing something wrong :package: 

Lgtm

**Pull request merged**
