### PR TITLE
Perf 662 adding uss to smem collector

### PR DESCRIPTION
**Pull request by zainahamid**
1. Added uss stats to smem.go
2. Made test changes to smem_test.go to account for changes in smem.go

These changes have been verified by running make

### CODE REVIEW

**Comment by avadhutp** [comment]
👍  Ship it!

**Comment by dichiarafrancesco** [comment]
+1

**Comment by avadhutp** [comment]
@zainahamid Hey, this is good to go. @dichiarafrancesco will bundle it and release it with the next version of fullerite next week.

**Comment by dichiarafrancesco** [comment]
@zainahamid remember to enable the new `uss` metrics through a puppet change.

**Pull request merged**
