### PR TITLE
Add asynchronous collector interval exec

### PR DESCRIPTION
**Pull request by tiras-j**
This is a bit messy, and if there is a better way to asynchronously monitor execution of a go routine I'd be happy to learn about it, but this should solve two issues that were present:

1. We were not executing collections at the correct intervals. Before we would execute the collector and then sleep for the duration *sequentially*. Such that the time it takes to execute the collector was not factored into the duration of the interval we'd wait before running it again. As such rather than running the collector on the exact interval every time, we'd wait an interval's worth of time between the end of one collection and the start of the next. However a simple ticker would solve that issue alone and this code is much more messy than that, so on to numero dos --

2. Running the go collection in a separate go routine with a boolean channel to indicate completion allows us to tick exactly at every interval (since we won't be blocking on the collector.Collect() call) and let's us see if we've overrun the collection interval. Thus we can add some kind of handler code there. What we want to do, I have no idea, but this will give us the option, whether it's simply logging that we are overrunning our interval or stopping the ticker and exiting this collector altogether at least we have the option. 

I'm very unfamiliar with Go, so I'm mostly presenting this PR to get some feedback and spawn some discussion on the current sequential way we do collection intervals.

EDIT:
Also the simple solution for the first case above would simply be to use a ticker and block on the collection call directly. This would look as so:
```go
ticker := time.NewTicker(time.Duration(collector.Interval()) * time.Second)
for t := range ticker.C {
    collector.Collect()
}
```
I'm not certain whether the ticker channel will drop ticks that are not ready to be received but I *think* that they will. Meaning if we were to overrun a given collection interval we'd miss the next tick altogether.

Edit 2:
Indeed it does drop ticks when client is not ready. From source:
> 	// Give the channel a 1-element time buffer.
>	// If the client falls behind while reading, we drop ticks
>      // on the floor until the client catches up.

### CODE REVIEW

**Comment by tsheasha** [comment]
Hey @tiras-j I am currently taking a stab at this with METRICS-170, and have implemented a ticker indeed as I mentioned in #125 , however making the collection happen in a separate go routine is very dangerous the way it is now. Here is why: Imagine the collection takes 1 hour to run. But you set an interval of 60 seconds. First of all we need to acknowledge that this colelciton is already happening in a go routine as per https://github.com/Yelp/fullerite/blob/master/src/fullerite/collectors.go#L34 . Nested go routines are fine but risky. In this case you will create a go routine for each of the collection intervals of 60 seconds so by the end of the hour you will have 60 go routines running all because the coplleciton is taking longer than it should.

What I am trying to do in METRICS-170 and #125  is terminate long running collectors and log the error and emit a metric like I do in diamond scheduler.py

Hope that helps!

**Comment by gnufied** [comment]
Yep, trying to factor in collection time into interval and letting same collector run concurrently multiple times is dangerous. It will causes all sort of problems since same collector is not meant to be executed paralley or in other words is not re-entrant.

**Comment by tiras-j** [comment]
Yep definitely, although this code currently will not launch another collector until the current goroutine thread is complete. All it allows is the ability to identify that we have in fact overrun our collection interval and we can do something about it. That being said I like @tsheasha idea better than this since there is no simple way to kill an active goroutine so keeping the execution path inside our same thread would be ideal (his AfterTimePanic/Defer solution we talked about briefly on irc).

**Comment by gnufied** [comment]
drat, you are right. I read your comment and didn't see the code. since I haven't seen the discussion IRC discussion - I will wait for code.

**Pull request closed without merging**
