### PR TITLE
Treat Threads_created as counter as per METRICS-86

### PR DESCRIPTION
**Pull request by tiras-j**
As per this ticket, Threads_created is a monotonically increasing value
and as such should be treated as a counter (such that the rollup is
the time derivative of the value). This change ensures that the value
is derivated before being reported as a gauge, which results in the
dx/dt value being monitored.

### CODE REVIEW

**Comment by tiras-j** [comment]
I still want to verify with jsnyder that this is the behavior she wants. This is in fact a counter value (implicit in the fact that it monotonically increases) however it does so quite slowly, meaning the majority of the time the dx/dt will be 0.

**Comment by poros** [comment]
Out of curiosity, is it a "cumulative counter" or a real counter?

**Comment by tiras-j** [comment]
https://support.signalfx.com/hc/en-us/articles/201213445-Choose-the-right-metric-type-for-your-data

Pretty much the same as counters but a couple semantic differences, as well as SFX being aware that the value may rollover on 32/64bit integer limit.

**Comment by tsheasha** [comment]
@tiras-j As per the work I did with the HttpdCollector for the TotalAccesses issues if you recall that, the recommended approach here is to *keep* this reported as a gauge from diamond and change it in the catalog on SFX to be a cumulative counter. until we have a way to report 'cumulative counter' types from diamond to fullerite. *since fullerite already supports this*

Reporting it as a counter as this PR is doing will break since this metric will go through the code path of the derivative which is not really what we want to do. A cumulative counter is basically reported as a gauge and sfx agrees :) :-
"It is just like capturing a gauge." - https://support.signalfx.com/hc/en-us/articles/201213445-Choose-the-right-metric-type-for-your-data

makes sense?

**Comment by tiras-j** [comment]
This change wouldn't actually report it as a counter, it would merely make sure that the Diamond collector takes the derivative of the counted value and reports it as a gauge (which is actually correct), basically doing all the computation that SFX would do on the local side. Not the best but its the minimal change for the diamond collector. Does forcing SFX to see it as a cumulative counter even when it's calling itself a gauge work? I'm definitely happy to try that.

Also I've implemented this change on a live dev box (for a few moments) and SFX handles it just fine since rather than changing the reported type we're merely 'fixing' the value to actually be a gauge value (the dx/dt of a counter) and reporting it the same way.

**Comment by tsheasha** [comment]
Well @tiras-j if you do the derivative and report it as a gauge sfx will guve you weird results on rollover valies since wehtehr the derivative will ignore negatives or not the set of points reported after the rollover will be inaccurate
 If you however report it as a gauge and configure it on sfx catalog as a cummulative counter thay will take care of itself. To answer your question .. You do not need any changed to the collector all the work will be done on the sfx side. Inplementing a cummulative counter type would be a nice to have though but not kecessary for your task to work. I apologise if that was not clear from my side earlier. Hope that helps

**Comment by tiras-j** [comment]
Ok so SFX can forcibly treat it however you'd like? Then yea that's definitely a better solution, since I'm not certain how the diamond derivation would handle a rollover (likely it would be a large negative spike for a single interval and then return to normal, since it used that last value and just does a delta *I think*). But yea I'll go ahead and close this PR and make an updated comment in Jira about this discussion and mark that I'll make the change on the SFX side.

**Pull request closed without merging**
