### PR TITLE
Only remove files/user on purge for deb package

### PR DESCRIPTION
**Pull request by gnufied**
This PR adds `postrm` for debian package and ensures that `fuller` user and some of the owned files by the user are deleted when package gets uninstalled by `purge` (something like apt-get purge)

This will bring it very close to debian packaging guidelines. Redis package for example does similar thing - http://bazaar.launchpad.net/~ubuntu-branches/ubuntu/trusty/redis/trusty/view/head:/debian/redis-server.postrm

### CODE REVIEW

**Comment by gnufied** [comment]
I have tested this inside vagrant and it seems to be working okay.

**Comment by tsheasha** [comment]
What issue is this trying to resolve? Stopping the service before installation can be done by software like puppet that runs a service restart once the version of the module changes.

**Comment by gnufied** [comment]
As per `fpm` docs, if we specify a `before-upgrade` script, `before-rm` script will not run in case of upgrades. 

So that is what I am trying to accomplish here. `before-upgrade` script does what partly `before-rm` was supposed to do except removing the `fuller` user.

**Comment by tsheasha** [comment]
we want to remove the user before installing / upgrading since we want to remove anything owned by that user before a fresh install. This is to handle configuration changes to the user's specs or if we change the dir we log to etc .. we want to remove unused ones

**Comment by gnufied** [comment]
I have verified that after this change, fullerite is merely stopped on upgrade or remove. Also, I have verified that on `apt-get purge fullerite` - `fuller` user gets deleted and `/var/log/fullerite` removed.

**Comment by tsheasha** [comment]
+1

**Comment by poros** [comment]
+1

**Pull request merged**
