### PR TITLE
Send cpu aggregated stats

### PR DESCRIPTION
**Pull request by dichiarafrancesco**
We want to send (cpu.user + cpu.nice) and (cpu.irq + cpu.softirq) in order to reduce the number of metrics emitted by the cpu collector. 
It's backward compatible.

### CODE REVIEW

**Comment by gnufied** [comment]
If I understand this correctly - if `enableAggregation` is true - we are still going to send individual `user`, `nice`, `irq` metrics as well as aggregated metrics. So enabling this collector will temporarily increase the number of metrics emitted, correct?

**Comment by dichiarafrancesco** [comment]
yeah! we can blacklist the ones we don't want through a config change!

**Comment by gnufied** [comment]
:shipit:

**Comment by venkey-ariv** [comment]
:shipit:

**Pull request merged**
