### PR TITLE
Run the tests for the diamond collectors

### PR DESCRIPTION
**Pull request by tsheasha**
With this commit you can run tests for diamond collectors. Since, not
all tests will pass, whether due to non-exsistent files or libs ..etc
and for the fact that I could not fix *all* the tests, you can run tests
for your own collector as follows from the `src/diamond` directory:-
    `$ python test.py -c $COLLECTOR_DIR_NAME`

For example to run the tests for tcp collector:-
    `$python test.py -c tcp`

### CODE REVIEW

**Comment by gnufied** [comment]
I think a better code organization would be:

```
src
|----- diamond/diamond/<move_all_source_here>
|----- diamond/tests
```

It will be more consistent with how we organize typical python packages but will require more changes in how we build this package etc.

**Comment by tsheasha** [comment]
I think this would make more sense if this were a python project. However this is a python subset of a go project. That is why i assume @poros  decided to give it this structure when migrating it from upstream diamond. IMO this is out of the scope of this PR as well.

**Comment by poros** [comment]
Being a plugin system, I thought that it was easier for users to just drop their collectors in fullerite/diamond. I didn't consider at all where to put the eventual test folder, though...

**Comment by poros** [comment]
Since most of this file comes from diamond, I wouldn't go much in implementation details. This PR is for sure an improvement compared to "no tests", so +1 :)

In the bright future, maybe we could even extend the CI workflow also to the diamond part

**Comment by tsheasha** [comment]
@poros that CI workflow part is indeed planned for the future, if I get time during the weekend to make all the tests for the current collectors to pass, maybe sometime early next week I will push a PR to include the tests in the CI workflow

**Comment by tiras-j** [comment]
+1 looks good.

**Comment by zachm** [comment]
+1 looks good. Merging.

**Pull request merged**
