### PR TITLE
use fullerite.conf from container

### PR DESCRIPTION
**Pull request by ChristianKniep**
This will pull the DockerStats via a bind-mounted docker socket.

### CODE REVIEW

**Comment by tsheasha** [comment]
+1

**Comment by tsheasha** [comment]
doesn't this make Pull request https://github.com/Yelp/fullerite/pull/192

**Comment by ChristianKniep** [comment]
#192 is meant to be to cover a StatsD handler. This one just uses pure Graphite.

**Comment by tsheasha** [comment]
apologies I meant #193

**Comment by ChristianKniep** [comment]
Yeah, I guess I got all exited with the PR, so that I merged them into my master and since I branched from the new master.... <lengthy_stupid_explaination_here>

I'll try to provide better patches in the future. If you could help me out by maybe just merge the latest one.

**Comment by tsheasha** [comment]
Done, merge #193 closing this one

**Pull request merged**
