### PR TITLE
Some scribe stats are cumulative counters

### PR DESCRIPTION
**Pull request by tsheasha**

### CODE REVIEW

**Comment by poros** [comment]
I honestly don't know which scribe metrics are cumulative counters and which ones are gauges...
But the PR seems legit
+1 (for what it's worth)

**Comment by tsheasha** [comment]
@poros I did my testing adhoc I saw which metric timeseries were forever increasing and which were not and adjusted the types accordingly, fwiw

**Comment by tsheasha** [comment]
From the command we use for scribe_ctrl apparently we get *counters* so none of them are really gauges, so I changes that accordingly. @poros Also all current usage of these metrics by us have the gauge with the Rate of Change analytical function set so it is acting as a rate/s rollup, so let's make it that way.

**Comment by poros** [comment]
Cool, thanks for spending time double checking all metrics.
+1 again

**Comment by dichiarafrancesco** [comment]
lg2m

**Pull request merged**
