### PR TITLE
Capturing the commandline argument and using correct processName

### PR DESCRIPTION
**Pull request by tsheasha**
cmdLine() was not working as expected since the process would not still
be there when the command line is being read. Now passing it forward
correctly, with tests :)
ProcessName was not being used anywhere so I am using that now if it is
set not always stat.Comm, that should only be the default if no
processName is defined

### CODE REVIEW

**Comment by avadhutp** [comment]
Looks good to me. Ship it :+1:

**Comment by tsheasha** [comment]
bump @poros

**Comment by gnufied** [comment]
Looks good. :+1:

**Comment by poros** [comment]
Lgtm
+1

**Comment by ericchu94** [comment]
@tsheasha I thought `CmdLine()` only fails when the process has died in the middle of processing. If that is the case, then shouldn't we just drop the metric?

Why should the processName dimension have the value of ps.processName, the query string? How will that work with gh-36, when the query string becomes a regular expression?

**Comment by tsheasha** [comment]
@ericchu94 CmdLine() was being called twice, by the second time it got called the process could have exited and that was causing errors. I removed that step and made it only called once and in case it fails, I "continue" which means I drop the metrics, so I am not sure what you are referring to.

As for ps.processName, I will fix that now

**Comment by ericchu94** [comment]
@tsheasha ship it

**Pull request merged**
