### PR TITLE
Silence conntrack not existed from stderr

### PR DESCRIPTION
**Pull request by tsheasha**

### CODE REVIEW

**Comment by poros** [comment]
It seems a pretty important info to me. Why do you  want to silence? Do all the other collectors avoid to report this kind of things?

**Comment by tsheasha** [comment]
@poros silencing this info is basically redirecting it to debug in case someone is interested to read it there. However logging this to stderr does not make lots of sense since since this is not an error of the collector, it means this collector is not reporting metrics since there are no metrics to report *now*. No other collector afaict does this. This seems like debug info rather than error info.

**Comment by poros** [comment]
It sounds like a good reason. +1

**Comment by gnufied** [comment]
:shipit:

**Pull request merged**
