### PR TITLE
Remove fullerite user once and for all

### PR DESCRIPTION
**Pull request by tsheasha**

### CODE REVIEW

**Comment by gnufied** [comment]
The readme still says it runs as user fullerite user. Should we update that as well?

**Comment by tsheasha** [comment]
done

**Comment by gnufied** [comment]
:shipit:

**Comment by gnufied** [comment]
The systemd scripts still use `fullerite` user. Sorry for finding this after giving :ship:

**Comment by tsheasha** [comment]
the sysconfig as well has that user

**Comment by poros** [comment]
+1

**Pull request merged**
