### PR TITLE
Added network usage stats to docker collector.

### PR DESCRIPTION
**Pull request by avadhutp**
Need these for monitoring network utilization on docker containers.

### CODE REVIEW

**Comment by avadhutp** [comment]
cc @drolando, @dichiarafrancesco

**Comment by poros** [comment]
lgtm

**Comment by zachm** [comment]
lgtm

**Comment by tsheasha** [comment]
My only objection is that it is not tested yet inside the docker_stats_test.go, would you mind adding tests for that @avadhutp

**Comment by avadhutp** [comment]
@tsheasha on it.

**Comment by avadhutp** [comment]
new tests added, can I get a shipit :-)

**Comment by tsheasha** [comment]
@avadhutp ship it!

**Comment by zachm** [comment]
@avadhutp you're in :) I'll be bumping Fullerite internally either tomorrow or Thursday.

**Pull request merged**
