### PR TITLE
Do not override collecotr names from other collectors

### PR DESCRIPTION
**Pull request by tsheasha**
Like Diamond

### CODE REVIEW

**Comment by gnufied** [comment]
How about adding a test for this, so as we don't have regressions?

**Comment by tsheasha** [comment]
This means that I will be testing go's dictionary existence funciton

**Comment by gnufied** [comment]
No it means we will be testing if metric read from channel includes a `collector` field we don't provide our own value

**Comment by tsheasha** [comment]
There is no logic to ignore an incoming metric other than checking for the field we are overriding in a dictionary using go's dictionary exists function. This makes no sense to me.

**Comment by gnufied** [comment]
So basically what I would do is, setup a collector with a channel and write a test metric to it and then ensure that `metrics`  channel receives a metric with `collector` specified not overridden.

**Comment by tsheasha** [comment]
I see no value in testing very basic functionality, so I am dropping this comment

**Comment by dichiarafrancesco** [comment]
+1

**Comment by gnufied** [comment]
I could be wrong but in my book - if a code branches (such as here via `if` condition) it should be tested. Any static code analysis tool you pick, they all recommend code branching to be tested. The cost of doing so is not very high here.

I won't argue further though and leave this for others to decide.

**Comment by chrisenuf** [comment]
ship it

**Comment by tiras-j** [comment]
Ship it!

**Pull request merged**
